회원가입 API
wecode-bootcamp-korea/39-1st-39cm-backend pull request #3
Opened 2022-11-16 09:04 UTC by LEEDONGKEN

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 API 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 API 기능 구현
- gender 에 '남자', '여자' 외 입력을 하게 되면 key error 발생
- users table에서는 gender_id는 int를 받아 '남자' 입력 시 1, '여자' 입력 시 2로 변환하는 콜백함수 생성 
- 이메일, 비밀번호(영문포함-소문자, 숫자포함, 8-20자 이내) 유효성 검사 

<img width="492" alt="스크린샷 2022-11-16 오후 12 19 01" src="https://user-images.githubusercontent.com/113091695/202135867-6b095fb0-c674-46d2-a0ff-ce0ba7381513.png">

-bcrypt를 활용해 비밀번호 hash 하여 저장함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 에러 체크를 통해 에러를 잡아내면 디버깅이 빠르다는 것을 알게됐습니다. 
- 정규표현식에 대해 탐구하는 시간을 가졌습니다. 
- 사용자는 문자를 입력하고 테이블은 int를 받을 때 변환하는 함수를 만들어 성공했습니다.  

<br />

## :: 기타 질문 및 특이 사항
- userService 파일에 있는 genderCheck 콜백함수가 긴 것 같아 좀 더 효율적인 코드가 있을 지 궁금합니다.

2022-11-17 01:26 UTC, LEEDONGKEN commented
## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 회원가입 API 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원가입 API 기능 구현
- gender 에 '남자', '여자' 외 입력을 하게 되면 key error 발생
- users table에서는 gender_id는 int를 받아 '남자' 입력 시 1, '여자' 입력 시 2로 변환하는 콜백함수 생성 
- 이메일, 비밀번호(영문포함-소문자, 숫자포함, 8-20자 이내) 유효성 검사 

<img width="492" alt="스크린샷 2022-11-16 오후 12 19 01" src="https://user-images.githubusercontent.com/113091695/202135867-6b095fb0-c674-46d2-a0ff-ce0ba7381513.png">

-bcrypt를 활용해 비밀번호 hash 하여 저장함

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 에러 체크를 통해 에러를 잡아내면 디버깅이 빠르다는 것을 알게됐습니다. 
- 정규표현식에 대해 탐구하는 시간을 가졌습니다. 
- 사용자는 문자를 입력하고 테이블은 int를 받을 때 변환하는 함수를 만들어 성공했습니다.  

<br />

## :: 기타 질문 및 특이 사항
- userService 파일에 있는 genderCheck 콜백함수가 긴 것 같아 좀 더 효율적인 코드가 있을 지 궁금합니다.

2022-11-17 02:21 UTC, bigfanoftim requested changes

2022-11-17 02:21 UTC, bigfanoftim commented on api/models/userDao.js
> +        throw error;
캐치된 에러의 메세지를 보내야 하는게 아닐까요?

어떤 에러가 발생하는 것과 상관없이 무조건 data input이 잘못되었다고 명시해버리면 안됩니다.

2022-11-17 05:07 UTC, LEEDONGKEN commented on api/models/userDao.js
> +        throw error;
controller 에서 회원가입 시 발생할 에러들은 대부분 잡아 중복 이메일 체크만 추가해서 에러발생 메시지를 수정했습니다.

2022-11-17 05:10 UTC, LEEDONGKEN commented
## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 반영 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 반영 수정
- controller 에서 회원가입 시 발생할 에러들은 대부분 잡아 중복 이메일 체크만 추가해서 에러발생 메시지를 수정했습니다.
- 그 외 에러가 발생했을 경우 'DATABASE ERROR' 로 반환되게 했습니다. 


<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 캐치된 에러를 정확히 아는 것이 중요하다고 느꼈습니다.

2022-11-17 05:52 UTC, bigfanoftim requested changes

2022-11-17 05:52 UTC, bigfanoftim commented on api/models/userDao.js
> +        }
중복된 이메일임을 클라이언트에 알리기 위해서는 예외처리 없이 DB에 에러를 내는 것이 아니라,
입력받은 이메일에 해당하는 유저의 존재 여부를 판단한 후 그에 맞게 서버에서 에러 핸들링하는 것이 좋습니다.

어차피 서버에서는 발생하는 에러에 대해 계속해서 로그를 관리할텐데 굳이 DB에 error raise 시켜 그쪽에서 문제가 발생했다고 오해를 불러일으킬 필요는 없을 것 같아요.

2022-11-17 08:42 UTC, LEEDONGKEN commented
## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 리뷰 반영 수정

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 리뷰 반영 수정
- 이메일 중복 관련 체크는 서비스레이어에서 해야 되는게 맞는거 같아 서비스레이어에 체크 로직을 짰습니다.



<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
-데이터베이스에서 직접적으로 오류를 받는게 치명적인 오류라는 것을 알게 됐습니다.

2022-11-18 01:35 UTC, bigfanoftim requested changes
들여쓰기가 전부 제각각인 것 같아요. 
아마 사용하고 계신 IDE에 설정에 따라 다르게 나올텐데 모두 스페이스 바로 맞춰서 컨트롤할 수 있는게 아니라면 prettier 적용을 추천드립니다.

2022-11-18 01:35 UTC, bigfanoftim commented on api/services/userService.js
> +    };
상수로 관리되는 데이터들은 보통 enum으로 관리하곤 합니다. JavaScript에서는 다음과 같이 객체 형태로 관리하게 됩니다.

```jsx
const Departure = {
  GMP: 1,
  PUS: 2,
  ...
}
```

하지만 위의 경우 객체가 수정될 수 있기 때문에 상수 데이터 관리 목적과는 반대되는 경우가 발생할 수 있습니다. 따라서 JavaScript의 `Object.freeze()`를 활용합니다.

```jsx
const Departure = Object.freeze({
  GMP: 1,
  PUS: 2,
  ...
})
```

함수를 정의하고 실행하는 것이 아니라 객체 형태로 관리하고 들어오는 값에 해당하는 value만 사용할 수 있도록 수정해 보세요!

2022-11-18 03:20 UTC, LEEDONGKEN commented on api/services/userService.js
> +    };
적용하니 코드 관리가 더 깔끔해졌어요.

2022-11-18 04:14 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-18 04:14 UTC, merged