[39cm]FEATURE: 상품 상세정보 조회하기, 상품 리스트 보기 기능 추가
wecode-bootcamp-korea/39-1st-39cm-backend pull request #4
Opened 2022-11-17 23:51 UTC by sangyeobhan

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
-상품 상세 정보 조회 기능과 상품 리스트 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 상세 정보 조회하기(getProductByProductId)
- isNaN을 통해 path parameter에 대한 유효성 검사를 진행
- 상품 이름, 상세 정보, 가격, 카테고리, 찜 숫자, 이미지, 리뷰를 반환
- 리퀘스트 예시 - http://127.0.0.1:3000/products/:productId

2. 상품 리스트 보기(getProducts)
- isNaN과 some()을 통해 query parameter에 대한 유효성 검사를 진행
- 정렬 옵션: 가격순(기본), 찜순, 리뷰순
- 필터 옵션: 색깔, 성별, 브랜드, 카테고리, 가격
- 리퀘스트 예시 - http://127.0.0.1:3000/products?limit=&offset=&sort=&color=&min_price=&max_price=&category=&brand=&product_gender=

3. 에러처리 유틸 파일 추가
`const err = new Error('BAD_REQUEST');
err.statusCode = 400;
throw err;
`
위와 같이 반복되는 코드가 가독성을 떨어뜨리는것 같아 Error 클래스를 상속하는 CustomError 클래스를 만들었습니다.
`class CustomError extends Error {
    constructor(errorMessage, statusCode) {
        super(errorMessage);
        this.statusCode = statusCode;
    }
}`
**사용 예시**
`throw new CustomError('BAD_REQUEST', 400);
`
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- mysqljs 의 공식 문서를 읽어보면서 플레이스홀더에 대한 이해 및 스스로 찾는 능력이 증가하였습니다.
- 클래스에 대한 이해가 증가하였습니다.
- some함수를 처음 사용해보면서 mdn을 읽는 능력이 증가하였습니다.
<br />

2022-11-18 03:06 UTC, bigfanoftim requested changes

2022-11-18 03:06 UTC, bigfanoftim commented on api/controllers/productController.js
> +        res.status(200).json({ product: product });
```suggestion
        res.status(200).json({ product });
```

아마 이렇게 작성하면 키 밸류 형태로 잘 들어갈겁니다 ㅎㅎ

2022-11-18 03:06 UTC, bigfanoftim commented on api/controllers/productController.js
> +        }
```JavaScript
const { limit, offset, ... } = req.query
```

구조분해 할당 사용하면 가독성이 더 좋을 것 같아요~

2022-11-18 03:50 UTC, sangyeobhan commented
## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 정보 조회 기능과 상품 리스트 기능 추가


<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. res.json() 함수내의 변수 형식 변경
- `res.json({product: product})` 로 보내던 형식을 동일하게 작동하는 `res.json({product})`로 변경하였습니다.

2. 구조분해 할당을 통한 가독성 향상
- req.query내의 프로퍼티들을 구조분해 할당함으로서 가독성을 향상하였습니다.

3. 변경사항 적용 후 테스트 완료하였습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 구조분해 할당 과정에서 `{ color, brand, sort, ...numberOptions } = req.query` 와 같이 rest parameter를 사용할 연구를 했으나 이를 다시 함수 호출할때 spread하는 과정에서 순서 보장에 대해 어려움을 겪었습니다. 결국 구조분해 할당 과정에서 각각 변수 지정을 해주는 것이 더 간결하다 생각했고 이를 선택했습니다. 이 과정에서 구조분해 할당과 rest parameter에 대한 이해가 증가하였습니다.

2022-11-18 04:31 UTC, bigfanoftim requested changes

2022-11-18 04:31 UTC, bigfanoftim commented on api/services/productService.js
> +    clause = clause.slice(0, clause.length - 4);
```JavaScript
const clause = [];
if (minPrice) clause += `p.price > ${minPrice}`;
// 반복...

const whereClauses = `WHERE ${clause.join(' AND ')}`
```

이렇게 작성하면 불필요한 로직이 좀 줄어들 것 같아요~

2022-11-18 04:31 UTC, bigfanoftim commented on api/services/productService.js
> +const getProducts = async (limit, offset, sort, minPrice, maxPrice, color, category, brand, productGender) => {
```suggestion
const getProducts = async (limit = 10, offset = 0, sort, minPrice, maxPrice, color, category, brand, productGender) => {
```
이런식으로 default를 줄 수 있어서 사실 몇몇 파라미터는 꼭 필요한 상황이 아니라면 복잡한 코드를 추가로 작성할 필요가 없긴 합니다 ㅎㅎ

2022-11-18 05:24 UTC, sangyeobhan commented
## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 상품 상세 정보 조회 기능과 상품 리스트 기능 추가


<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. arr.join을 사용해 가독성 향상
- 쿼리문 합성 과정에서 불필요한 코드들을 제거하여 가독성을 향상하였습니다.

2. default 값을 사용하여 가독성 향상
- offset 과 imit에 default값을 적용하여 불필요한 로직을 제거하였습니다.

3. 변경사항 적용 및 메인 머지 후 테스트 완료하였습니다.
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- offset, limit에 default 값 적용하는 과정에서 default parameter가 적용되지 않는 상황이 발생했고 확인해본 결과 req.query에 빈값이 들어올경우 undefined가 아니라 빈 스트링이 들어오는것을 확인하였습니다. 이 아이디어를 차용하여 buildLimitAndOffset 함수 내에 default 값을 적용하였습니다.

2022-11-21 01:42 UTC, bigfanoftim approved these changes
LGTM 👍

2022-11-21 01:42 UTC, merged